# Generated by Django 3.1.1 on 2020-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_action_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.BooleanField(default=True),
        ),
    ]
