# Generated by Django 3.1.1 on 2020-12-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201210_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
