# Generated by Django 3.1.1 on 2020-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_owner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
