# Generated by Django 3.1.1 on 2020-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201211_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
