# Generated by Django 3.1.1 on 2020-11-07 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=10)),
                ('start_date', models.DateField(blank=True)),
                ('deposite', models.IntegerField()),
                ('room_name', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('balance', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcore.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rent', models.IntegerField(default=0)),
                ('units', models.IntegerField(default=0)),
                ('price_per_unit', models.IntegerField(default=0)),
                ('electric_total', models.IntegerField(default=0)),
                ('water_bill', models.IntegerField(default=0)),
                ('wifi_charge', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcore.tenant')),
            ],
        ),
    ]
