# Generated by Django 3.1.1 on 2020-11-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
